//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryTask
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_PurchaseOrderDetail
    {
        public int PODID { get; set; }
        public Nullable<int> POID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> Qty { get; set; }
    
        public virtual tbl_Product tbl_Product { get; set; }
        public virtual tbl_PurchaseOrder tbl_PurchaseOrder { get; set; }
    }
}
